### ISSUE TITLE
Media Widget doesnt work properly with Opera GX

### ISSUE THREAD

**Issue by airfortech** [amnweb/yasb#482]
### Windows version

Windows 11

### Windows OS build

24H2

### YASB version installed

1.8.2

### Describe the bug

Opera GX portable:

- youtube: volume doesnt show
- when video changes automaticaly to next video, timeline doesnt update. It updates after I manualy move timeline or manualy change video

### Relevant log output

```shell
there is no log about this bug
```

**Comment by amnweb** [comment]
Open the YASB config file, set `debug: true`, open the terminal, and type `yasbc log`. Then open Opera and play some videos, (open YASB media popup) you’ll see something in the log like `Unknown source app in media_info....` Please share that log here.

About the other problem with the timeline: this started happening a few months ago when YouTube began testing their new player. I can’t do anything about it because the Windows media API doesn’t send all the data we need from YouTube, it’s probably a bug on their side.

**Comment by airfortech** [comment]
22:56:33,288 ←[0m←[94m   DEBUG←[0m←[0m: Unknown source app in session: 'OperaSoftware.OperaGXWebBrowser.1576276902' - consider adding to source_apps.py
22:57:19,523 ←[0m←[94m   DEBUG←[0m←[0m: MediaCallback: No active session
22:57:19,524 ←[0m←[94m   DEBUG←[0m←[0m: MediaCallback: No active session
22:57:19,526 ←[0m←[94m   DEBUG←[0m←[0m: MediaCallback: No active session
22:57:19,527 ←[0m←[94m   DEBUG←[0m←[0m: MediaCallback: No active session
22:57:19,796 ←[0m←[94m   DEBUG←[0m←[0m: Unknown source app in session: 'OperaSoftware.OperaGXWebBrowser.1576276902' - consider adding to source_apps.py
22:57:19,846 ←[0m←[94m   DEBUG←[0m←[0m: Unknown source app in session: 'OperaSoftware.OperaGXWebBrowser.1576276902' - consider adding to source_apps.py
22:57:26,409 ←[0m←[94m   DEBUG←[0m←[0m: Unknown source app in session: 'OperaSoftware.OperaGXWebBrowser.1576276902' - consider adding to source_apps.py

**Comment by amnweb** [comment]
Fixed.
If you want, you can test the latest artifact from this URL https://github.com/amnweb/yasb/actions/runs/18261983084

**Comment by airfortech** [comment]
thx, i checked it and it works now with Opera GX. Timelile issue still exists but like you said its API problem.

**Comment by amnweb** [comment]
> thx, i checked it and it works now with Opera GX. Timelile issue still exists but like you said its API problem.

We can’t do anything about it for now, and as far as I know, this is only a YouTube issue, all other apps and sites work fine.
